# Imports video reader ('read_video') and writer ('save_video') helper functions from the local 'utils' module.
from utils import read_video, save_video

# Imports the 'PlayerTracker' class from the local 'trackers' package for handling YOLO object detection and tracking.
from trackers import PlayerTracker

# Defines the main execution entry function for the tracking pipeline script.
def main():

    # Loads frames from the target MP4 video file and stores them as a list of NumPy image arrays.
    video_frames = read_video("input_video/video_1.mp4")

    # Instantiates PlayerTracker using a custom trained YOLO model weights file for basketball players.
    player_tracker = PlayerTracker("model/basketball_player_detection_training.pt")

    # Runs player object detection and tracking across video frames (or reads cached tracking data if stub mode is enabled).
    tracks = player_tracker.get_object_tracks(video_frames, read_from_stub=False,stub_path="stubs/player_tracks.pkl")

    # Prints total frame count loaded from the source video to the console.
    print(f"Number of frames: {len(video_frames)}")

    # Prints total number of tracked frame output entries generated by the object tracker.
    print(f"Number of tracks: {len(tracks)}")

    # Encodes and writes processed video frames list to output AVI video file destination.
    save_video(video_frames,"output_video/output_video_1.avi")

# Runs the main() function only when executed directly as the primary script.
if __name__ == "__main__":
    main()
